### ISSUE TITLE
您好，运行到第五帧就直接卡死了

### ISSUE THREAD

**Issue by 1999mzs** [mianfeng/paddle_MTMCT#2]
运行到第五帧就直接卡死了，是什么原因呢

**Comment by 1999mzs** [comment]
![Uploading 2e1bb710bd8031115334483cbaedca7.png…]()

**Comment by mianfeng** [comment]
请问是所有视频都会这样吗 ，还有是固定第五帧还是运行后某一帧，有什么报错信息吗

**Comment by 1999mzs** [comment]
> 请问是所有视频都会这样吗 ，还有是固定第五帧还是运行后某一帧，有什么报错信息吗

每个视频都是，刚刚上传照片上传不了，没有报错信息，就是直接卡死了

**Comment by 1999mzs** [comment]
<img width="245" alt="2e1bb710bd8031115334483cbaedca7" src="https://github.com/mianfeng/paddle_MTMCT/assets/114285597/5b0a63b8-27c2-4b15-9e32-981c94cf60c9">
<img width="145" alt="9c99949f9f5ffd51d2af763a0f68c5f" src="https://github.com/mianfeng/paddle_MTMCT/assets/114285597/e14f9135-b173-425a-91c2-716e62121016">
<img width="333" alt="df4b60b7f10606202b754ab6f331b8e" src="https://github.com/mianfeng/paddle_MTMCT/assets/114285597/8aacca47-dcff-4d75-8347-ba3d11b0b702">

**Comment by 1999mzs** [comment]
再换了不同的电脑之后还是在第五帧出现了未响应的状态，请问您遇到过吗，或者您能提供一点修改思路吗？

**Comment by mianfeng** [comment]
目前还没有遇到过这种情况，不过可以看一下这个进程的内存占用情况，看看是不是内存的问题呢

**Comment by nongmo007** [comment]
> 再换了不同的电脑之后还是在第五帧出现了未响应的状态，请问您遇到过吗，或者您能提供一点修改思路吗？

您好，我也遇到了同样的问题，请问后来您解决了吗？

**Comment by MustakMU** [comment]
Hi @mianfeng 
I' unable to run you code using rtsp video stream, could you please explain how to run?
I've copied the pptracking and python folder from paddledetection to your repo, and following same instruction, but at the begging of the video itself the I'm getting the following error, please help
```
(paddle-dev) mustak@mustak-pc:~/detection/paddle_MTMCT$ python3 pipeline_muti.py --config config/infer_cfg_pphuman.yml --rtsp=rtsp://test1234:test1234@192.168.101.4:554/stream1  --device=gpu
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
-----------  Running Arguments -----------
ATTR:
  batch_size: 8
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
DET:
  batch_size: 1
  model_dir: output_inference/mot_ppyoloe_s_36e_pipeline/
ID_BASED_CLSACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPHGNet_tiny_calling_halfbody.zip
  skip_frame_num: 2
  threshold: 0.8
ID_BASED_DETACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ppyoloe_crn_s_80e_smoking_visdrone.zip
  skip_frame_num: 2
  threshold: 0.6
KPT:
  batch_size: 8
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
MOT:
  batch_size: 1
  enable: false
  model_dir: output_inference/mot_ppyoloe_s_36e_pipeline/
  skip_frame_num: 1
  tracker_config: pptracking/python/tracker_config.yml
REID:
  batch_size: 16
  enable: true
  model_dir: output_inference/reid_model/
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: false
  max_frames: 50
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
VIDEO_ACTION:
  batch_size: 1
  enable: false
  frame_len: 8
  model_dir: https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ppTSM_fight.zip
  sample_freq: 7
  short_size: 340
  target_size: 320
attr_thresh: 0.8
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
rtsp
MTMCT enabled
DET  model dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
mot_model_dir model_dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
KPT  model dir:  /home/mustak/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
REID  model dir:  output_inference/reid_model/
-----------  Model Configuration -----------
Model Arch: DeepSORT
Transform Order: 
--transform op: LetterBoxResize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
support_model  YOLO
support_model  YOLO
support_model  YOLO
support_model  YOLO
support_model  YOLO
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: Permute
--------------------------------------------
MTMCT enabled
DET  model dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
mot_model_dir model_dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
KPT  model dir:  /home/mustak/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
REID  model dir:  output_inference/reid_model/
-----------  Model Configuration -----------
Model Arch: DeepSORT
Transform Order: 
--transform op: LetterBoxResize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
support_model  YOLO
support_model  YOLO
support_model  YOLO
support_model  YOLO
support_model  YOLO
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: Permute
--------------------------------------------
video fps: 15, frame_count: -1537228672809129
video fps: 15, frame_count: -1537228672809129
OpenCV: FFMPEG: tag 0x31766c66/'flv1' is not supported with codec id 21 and format 'flv / FLV (Flash Video)'
OpenCV: FFMPEG: fallback to use tag 0x00000002/'????'
OpenCV: FFMPEG: tag 0x31766c66/'flv1' is not supported with codec id 21 and format 'flv / FLV (Flash Video)'
OpenCV: FFMPEG: fallback to use tag 0x00000002/'????'
[WARNNING] No object detected.
[] None [] [] []
Exception in thread 001:
Traceback (most recent call last):
  File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 524, in run
    self.predict_video(input, thread_idx=thread_idx,threadQueue=threadQueue,frameQueue=frameQueue)
  File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 618, in predict_video
    res = self.mot_predictor.predict_image(
  File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 563, in predict_image
    tracking_outs = self.tracking(det_result)
  File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 319, in tracking
    online_targets = self.tracker.update(pred_dets, pred_embs)
  File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot/tracker/deepsort_tracker.py", line 104, in update
    for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
TypeError: 'NoneType' object is not iterable
[WARNNING] No object detected.
[] None [] [] []
Exception in thread 000:
Traceback (most recent call last):
  File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 524, in run
    self.predict_video(input, thread_idx=thread_idx,threadQueue=threadQueue,frameQueue=frameQueue)
  File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 618, in predict_video
    res = self.mot_predictor.predict_image(
  File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 563, in predict_image
    tracking_outs = self.tracking(det_result)
  File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 319, in tracking
    online_targets = self.tracker.update(pred_dets, pred_embs)
  File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot/tracker/deepsort_tracker.py", line 104, in update
    for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
TypeError: 'NoneType' object is not iterable
```

**Comment by mianfeng** [comment]
> 嗨，我无法使用 rtsp 视频流运行您的代码，您能解释一下如何运行吗？我已将 pptracking 和 python 文件夹从 paddledetection 复制到您的存储库，并按照相同的说明进行作，但在视频本身的恳求下，我收到了以下错误，请帮忙
> 
> ```
> (paddle-dev) mustak@mustak-pc:~/detection/paddle_MTMCT$ python3 pipeline_muti.py --config config/infer_cfg_pphuman.yml --rtsp=rtsp://test1234:test1234@192.168.101.4:554/stream1  --device=gpu
> Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
> -----------  Running Arguments -----------
> ATTR:
>   batch_size: 8
>   enable: false
>   model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
> DET:
>   batch_size: 1
>   model_dir: output_inference/mot_ppyoloe_s_36e_pipeline/
> ID_BASED_CLSACTION:
>   batch_size: 8
>   display_frames: 80
>   enable: false
>   model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPHGNet_tiny_calling_halfbody.zip
>   skip_frame_num: 2
>   threshold: 0.8
> ID_BASED_DETACTION:
>   batch_size: 8
>   display_frames: 80
>   enable: false
>   model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ppyoloe_crn_s_80e_smoking_visdrone.zip
>   skip_frame_num: 2
>   threshold: 0.6
> KPT:
>   batch_size: 8
>   model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
> MOT:
>   batch_size: 1
>   enable: false
>   model_dir: output_inference/mot_ppyoloe_s_36e_pipeline/
>   skip_frame_num: 1
>   tracker_config: pptracking/python/tracker_config.yml
> REID:
>   batch_size: 16
>   enable: true
>   model_dir: output_inference/reid_model/
> SKELETON_ACTION:
>   batch_size: 1
>   coord_size:
>   - 384
>   - 512
>   display_frames: 80
>   enable: false
>   max_frames: 50
>   model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
> VIDEO_ACTION:
>   batch_size: 1
>   enable: false
>   frame_len: 8
>   model_dir: https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ppTSM_fight.zip
>   sample_freq: 7
>   short_size: 340
>   target_size: 320
> attr_thresh: 0.8
> crop_thresh: 0.5
> kpt_thresh: 0.2
> visual: true
> warmup_frame: 50
> 
> ------------------------------------------
> rtsp
> MTMCT enabled
> DET  model dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
> mot_model_dir model_dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
> KPT  model dir:  /home/mustak/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
> REID  model dir:  output_inference/reid_model/
> -----------  Model Configuration -----------
> Model Arch: DeepSORT
> Transform Order: 
> --transform op: LetterBoxResize
> --transform op: NormalizeImage
> --transform op: Permute
> --------------------------------------------
> support_model  YOLO
> support_model  YOLO
> support_model  YOLO
> support_model  YOLO
> support_model  YOLO
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Transform Order: 
> --transform op: Resize
> --transform op: Permute
> --------------------------------------------
> MTMCT enabled
> DET  model dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
> mot_model_dir model_dir:  output_inference/mot_ppyoloe_s_36e_pipeline/
> KPT  model dir:  /home/mustak/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
> REID  model dir:  output_inference/reid_model/
> -----------  Model Configuration -----------
> Model Arch: DeepSORT
> Transform Order: 
> --transform op: LetterBoxResize
> --transform op: NormalizeImage
> --transform op: Permute
> --------------------------------------------
> support_model  YOLO
> support_model  YOLO
> support_model  YOLO
> support_model  YOLO
> support_model  YOLO
> -----------  Model Configuration -----------
> Model Arch: YOLO
> Transform Order: 
> --transform op: Resize
> --transform op: Permute
> --------------------------------------------
> video fps: 15, frame_count: -1537228672809129
> video fps: 15, frame_count: -1537228672809129
> OpenCV: FFMPEG: tag 0x31766c66/'flv1' is not supported with codec id 21 and format 'flv / FLV (Flash Video)'
> OpenCV: FFMPEG: fallback to use tag 0x00000002/'????'
> OpenCV: FFMPEG: tag 0x31766c66/'flv1' is not supported with codec id 21 and format 'flv / FLV (Flash Video)'
> OpenCV: FFMPEG: fallback to use tag 0x00000002/'????'
> [WARNNING] No object detected.
> [] None [] [] []
> Exception in thread 001:
> Traceback (most recent call last):
>   File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 524, in run
>     self.predict_video(input, thread_idx=thread_idx,threadQueue=threadQueue,frameQueue=frameQueue)
>   File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 618, in predict_video
>     res = self.mot_predictor.predict_image(
>   File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 563, in predict_image
>     tracking_outs = self.tracking(det_result)
>   File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 319, in tracking
>     online_targets = self.tracker.update(pred_dets, pred_embs)
>   File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot/tracker/deepsort_tracker.py", line 104, in update
>     for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
> TypeError: 'NoneType' object is not iterable
> [WARNNING] No object detected.
> [] None [] [] []
> Exception in thread 000:
> Traceback (most recent call last):
>   File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/mustak/miniconda3/envs/paddle-dev/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 524, in run
>     self.predict_video(input, thread_idx=thread_idx,threadQueue=threadQueue,frameQueue=frameQueue)
>   File "/home/mustak/detection/paddle_MTMCT/pipeline_muti.py", line 618, in predict_video
>     res = self.mot_predictor.predict_image(
>   File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 563, in predict_image
>     tracking_outs = self.tracking(det_result)
>   File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot_sde_infer.py", line 319, in tracking
>     online_targets = self.tracker.update(pred_dets, pred_embs)
>   File "/home/mustak/detection/paddle_MTMCT/pptracking/python/mot/tracker/deepsort_tracker.py", line 104, in update
>     for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
> TypeError: 'NoneType' object is not iterable
> ```
这是我几年前的粗糙尝试，可能有很多bug，这个问题很可能是当视频流中没有人物目标出现，导致pred_dets 和 pred_embs 没有初始化，变成了 None
